<a href="https://colab.research.google.com/github/T0whed/Pytorch-Tutorial/blob/main/Introduction_To_Tensure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

**Tensors**

*   A torch.Tensor is a multi-dimensional Arrays, but full of fun things that make them  work better on GPU's(vs regular CPU)
*   default data type of float32
*   More suitable for deep learning than a numpy array





In [9]:
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [14]:
my_tensor = torch.arange(10)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#Reshape and View
my_tensor = my_tensor.reshape(2,5)

my_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
#Reshpe while number of items is unknown using -1
my_torch = my_tensor.reshape(2, -1)#view also work as like as reshape but there are some diff also
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([4, 5, 6, 7])


In [18]:
tensor_a + tensor_b

tensor([ 5,  7,  9, 11])

In [19]:
torch.add(tensor_a, tensor_b)

tensor([ 5,  7,  9, 11])

In [21]:
torch.subtract(tensor_a, tensor_b)

tensor([-3, -3, -3, -3])

In [22]:
torch.sub(tensor_b, tensor_a)

tensor([3, 3, 3, 3])

In [23]:
tensor_a * tensor_b

tensor([ 4, 10, 18, 28])

In [24]:
torch.multiply(tensor_a, tensor_b)

tensor([ 4, 10, 18, 28])

In [25]:
torch.mul(tensor_a, tensor_b)

tensor([ 4, 10, 18, 28])

In [26]:
torch.div(tensor_b, tensor_a)

tensor([4.0000, 2.5000, 2.0000, 1.7500])

In [29]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 1, 0, 3])

In [30]:
torch.pow(tensor_b, tensor_a)

tensor([   4,   25,  216, 2401])

In [31]:
tensor_a. mul(tensor_b)

tensor([ 4, 10, 18, 28])

In [33]:
tensor_a.div(tensor_b)

tensor([0.2500, 0.4000, 0.5000, 0.5714])

In [34]:
tensor_a

tensor([1, 2, 3, 4])

In [35]:
tensor_a.add(tensor_b)

tensor([ 5,  7,  9, 11])

In [36]:
tensor_a

tensor([1, 2, 3, 4])

In [37]:
tensor_a.add_(tensor_b)

tensor([ 5,  7,  9, 11])

In [38]:
tensor_a

tensor([ 5,  7,  9, 11])